# Generated by Django 4.1.4 on 2022-12-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="название")),
                ("sku", models.CharField(max_length=255, verbose_name="артикул")),
                ("price", models.CharField(max_length=255, verbose_name="цена")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("HAVE", "В наличии"),
                            ("ORDER", "Под заказ"),
                            ("WAIT", "Ожидается поступление"),
                            ("HAVENT", "Нет в наличии"),
                            ("NOTPROD", "Не производится"),
                        ],
                        max_length=10,
                        verbose_name="статус",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="images", verbose_name="изображение"),
                ),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
    ]
